Create React App structure
parfete/front pull request #2
Opened 2022-05-03 14:00 UTC by tosave04

Initialisation du projet
- `npx create-react-app my-app --template typescript`
- Première structure de dossiers (à décider ensemble) :
  - .devcontainer
  - public => Divers ajouté à la compilation
  - src
    - components =>Les composants de nos pages
    - pages => Les pages qui correspondent aux routes
    - styles => ex: CSS, à voir si l'on en a l'usage
- `react-router-dom` (Gestion des routes)
- `front.code-workspace` pour charger l'espace de travail sur VSCode
- Pages et Composants de démarrage pour l'équipe

2022-05-03 20:34 UTC, IngridDelteil commented
Hello !

Pour la structure des dossiers tout me va sauf que je ne comprends pas les dossiers avec nos noms ? Ca va compliquer les choses pour les imports je pense. Ne vaudrait-il mieux pas faire un dossier basics et features avec des sous-dossiers de features ce serait plus parlant que nos prénoms. Sachant que chacun saura sur quel composant il doit travailler. Car pour une feature on sera surement plusieurs dessus (chacun son composant). Et quand tu vas vouloir faire ton composant page tu vas devoir te rappeler qui a fait quoi pour importer les composants alors que par feature et avec des noms clairs c'est plus intuitif. Le dossier styles a priori avec tailwind il ne servira pas car tu mets les classes dans les composants directement et tu as un fichier tailwind.css à la racine du projet.
Par contre je ne comprends pas pourquoi tu as fait le create-react-app my-app au lieu de create-react-app parfete ? car un dossier my-app c'est pas très parlant sur nos postes. Je ne sais pas si ça peut se modifier après coup. 
Merci pour tout :-)

2022-05-03 22:34 UTC, tosave04 commented
Salut
L'appli a bien le nom "Parfete", j'ai juste indiqué le type de commande utilisé.
Les dossiers avec les noms c'est juste pour l'exemple et si vous voulez faire des tests avec des pull request.
La proposition c'est pour chaque features, les composants bien classes et les pages qui correspondent aux routes.

2022-05-03 22:44 UTC, IngridDelteil commented
Super alors Thomas ! Désolé de n'avoir pas bien compris dès le départ. D'où l'importance de communiquer :-) Merci pour les explications et pour ton travail.

2022-05-03 23:55 UTC, IngridDelteil requested changes
Concernant le router il est généralement mis au niveau du index et non app comme tous les providers car avec tailwind on aura de mémoire un provider de theme.
Concernant le App les routes n'impactent normalement que le main et donc on a une structure qui ressemble plus à ceci : 
`<>
      <Header />
      <Routes>
        <Route exact path='/' element={<Home />} />
        <Route
          exact
          path='/aventure/:prenom/:genre/:destination'
          element={<Aventure />}
        />
        <Route exact path='/renseignements/:planet' element={<Fiche />} />
        <Route exact path='/inscription' element={<Formulaire />} />
        <Route exact path='/systemesolaire' element={<Systeme />} />
        <Route path='*' element={<Oups />} />
      </Routes>
      <Footer />
    </>`
En utilisant un fragment comme ça tu gardes une structure html propre sans div inutiles avec header main footer. Après au choix soit tu mets <main> dans app et les composants pages return des fragments ou alors tu mets pas la balise <main> dans app mais chaque composant page devra return <main>, je ne sais pas quelle solution des deux est la meilleure.
Concernant l'arborescence je rajouterais un dossier assets pour les images et pour moi le dossier styles ne servira pas dans notre cas le style tailwind étant placé à la racine.
Concernant les composants j'ai pour habitude de déclarer avec const et fonction fléchée car plus lisible et apparemment d'après Mike c'est une bonne pratique surtout lorsqu'on utilise typescript.

2022-05-05 07:55 UTC, tosave04 commented
> Concernant le router il est généralement mis au niveau du index et non app comme tous les providers car avec tailwind on aura de mémoire un provider de theme.

Je prépare un autre commit avec quelques modifs, App j'avais tout simplement gardé la structure du `create` sans y toucher
- function => function fléché ça me va
- `Router` dans `index.tsx` ok
- `main` dans App me parait plus simple, c'est lié au design, ça évitera de s'en préoccuper pour les features
- J'ai modifié `styles` en `assets`, en principe ça ne servira qu'au design, je te laisse gérer les modifs si besoin

Pourras-tu t'occuper d'installer `Tailwind` ?

2022-05-05 08:02 UTC, IngridDelteil commented
Super ! 

Pour tailwind ok je m'en occuperais :-)

2022-05-05 08:09 UTC, IngridDelteil approved these changes

2022-05-05 08:11 UTC, merged